In [101]:
%load_ext pycodestyle_magic
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime

The pycodestyle_magic extension is already loaded. To reload it, use:
  %reload_ext pycodestyle_magic

In [112]:
df = pd.read_csv('rollercoaster.csv')
df.head()

,Name,Park,City/Region,City/State/Region,Country/Region,Geographic Region,Construction,Type,Status,Year/Date Opened,Height (feet),Speed (mph),Length (feet),Inversions (YES or NO),Number of Inversions,Drop (feet),Duration (min:sec),G Force,Vertical Angle (degrees)
0,10 Inversion Roller Coaster,Chimelong Paradise,Panyu,"Guangzhou, Guangdong",China,Asia,Steel,Sit Down,Operating,2006.0,98.4,45.0,2788.8,YES,10.0,NaN,1:32,NaN,NaN
1,Abismo,Parque de Atracciones de Madrid,Madrid,Madrid,Spain,Europe,Steel,Sit Down,Operating,2006.0,151.6,65.2,1476.4,YES,2.0,NaN,1:00,4,NaN
2,Adrenaline Peak,Oaks Amusement Park,Portland,Oregon,United States,North America,Steel,Sit Down,Operating,2018.0,72,45.0,1050.0,YES,3.0,NaN,NaN,NaN,97.0
3,Afterburn,Carowinds,Charlotte,North Carolina,United States,North America,Steel,Inverted,Operating,1999.0,113,62.0,2956.0,YES,6.0,NaN,2:47,NaN,NaN
4,Alpengeist,Busch Gardens Williamsburg,Williamsburg,Virginia,United States,North America,Steel,Inverted,Operating,1997.0,195,67.0,3828.0,YES,6.0,170,3:10,3.7,NaN

In [113]:
%%pycodestyle
df.loc[134, 'Duration (sec)'] = '0:00'
df.iloc[134]

Algorithm: (.5*gforce)((displacement/(2h/g*sin**2(theta))**.5)/10)(duration/ max(duration))+(speed/max(speed))+(height/(max(height))))

In [114]:
%%pycodestyle

import pandas as pd
import math

rollers = pd.read_csv('rollercoaster.csv')
rollers.columns = rollers.columns.str.strip()
rollers.columns
rollers.head()
rollers.at[111, 'Height (feet)'] = 200
rollers[111:112]
rollers['Height (feet)'] = rollers['Height (feet)'].astype(float)
rollers = rollers.rename(columns={"Height (feet)": "Height"})
rollers[['Name', 'Height']]
rollers = rollers.rename(columns={"Speed (mph)": "Speed"})
rollers[['Name', 'Speed']]
rollers = rollers.rename(columns={"Drop (feet)": "Drop"})
rollers = rollers.rename(columns={"Length (feet)": "Length"})
rollers = rollers.rename(columns={"Duration (min:sec)": "Duration"})


rollers[['Name', 'Drop']]
print(rollers.Height.max())
print(rollers.Speed.max())

In [115]:
%%pycodestyle
rollers.columns


rollers['G Force'] = pd.to_numeric(rollers['G Force'], errors='coerce')
rollers['Drop'] = pd.to_numeric(rollers['Drop'], errors='coerce')

rollers['Drop'] = rollers['Drop'].fillna(1)
rollers['G Force'] = rollers['G Force'].fillna(1)
rollers['Vertical Angle (degrees)'] = rollers
['Vertical Angle (degrees)'].fillna(1)

rollers['Vertical Angle (degrees)'] = rollers
['Vertical Angle (degrees)'].apply(math.radians)


# rollers['Drop']
rollers['Vertical Angle (degrees)']
# rollers.dtypes

In [116]:
%%pycodestyle
import math
math.sin(1)

In [117]:
%%pycodestyle
rollers['Score'] = .5*rollers
['G Force'] + ((rollers['Drop'] /
                (rollers['Vertical Angle (degrees)'].apply
                 (math.sin))) / (2*rollers['Drop'] / 9.8 *
                                 (rollers['Vertical Angle (degrees)'].
                                 apply(math.sin))**2)**.5)/10.
rollers['Score']